### ISSUE TITLE
indeError: list index out of range.

### ISSUE THREAD

**Issue by adienxy** [ablodge/AMR-enhanced-alignments#14]
Error occurred during when i run this command:
python align_with_pretrained_model.py -t api_response.json --subgraph-model ldc+little_prince.subgraph_params.pkl --relation-model ldc+little_prince.relation_params.pkl --reentrancy-model ldc+little_prince.reentrancy_params.pkl

**Comment by adienxy** [comment]
[amr] Loading AMRs from file: api_response.json
Loading model: ldc+little_prince.subgraph_params.pkl
Apply Rules = True
Preprocessing coverage: 0.00%
  0%|                                                                                                | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "align_with_pretrained_model.py", line 64, in <module>
    main()
  File "align_with_pretrained_model.py", line 36, in main
    sub_alignments = subgraph_model.align_all(eval_amrs)
  File "/mnt/home/adienxy/3_21_AMR_aspect/Amr_generator/leamr/leamr-master/models/subgraph_model.py", line 384, in align_all
    alignments = super().align_all(amrs, alignments, preprocess, debug)
  File "/mnt/home/adienxy/3_21_AMR_aspect/Amr_generator/leamr/leamr-master/models/base_model.py", line 102, in align_all
    aligns, scores = self.align(amr, alignments, n, unaligned, return_all=True)
  File "/mnt/home/adienxy/3_21_AMR_aspect/Amr_generator/leamr/leamr-master/models/subgraph_model.py", line 239, in align
    postprocess_subgraph(amr, alignments, tmp_align, english=ENGLISH)
  File "/mnt/home/adienxy/3_21_AMR_aspect/Amr_generator/leamr/leamr-master/rule_based/subgraph_rules.py", line 67, in postprocess_subgraph
    _postprocess_subgraph_english(amr, alignments, align)
  File "/mnt/home/adienxy/3_21_AMR_aspect/Amr_generator/leamr/leamr-master/rule_based/subgraph_rules.py", line 130, in _postprocess_subgraph_english
    if 'of' in [amr.tokens[t].lower() for t in align.tokens] and \
  File "/mnt/home/adienxy/3_21_AMR_aspect/Amr_generator/leamr/leamr-master/rule_based/subgraph_rules.py", line 130, in <listcomp>
    if 'of' in [amr.tokens[t].lower() for t in align.tokens] and \
IndexError: list index out of range

**Comment by Abhishek-P** [comment]
👍  added some debug prints and it tries to lookup alignment in an empty token list. 
Caveat: we were running it without neuralcoref since that dependency resolution seems to be broken
